<?php $marques = $this->getMarques(); ?>

<table class="marques">
    <thead style="text-align:center">
        <tr style="padding:20px 0; background-color:#636363; color:white">
            <td style="width:200px">Image</td>
            <td>Marque</td>
            <td>Produits associés</td>
        </tr>
    </thead>
    <tbody style="text-align:center">
        <?php foreach ($marques as $marque): ?>
            <tr style="padding:20px 0">
                <td>
                    <img style="width:90%; padding: 20px" src="<?php echo Mage::helper('virtual_marques')->getImageUrl($marque->getImageUrl()); ?>" title="<?php echo $marque->getName(); ?>">
                </td>
                <td><?php echo $marque->getName(); ?></td>
                <td>
                    <a target="_blank" href="<?php echo $this->helper('virtual_marques/data')->getMarqueUrl($marque); ?>">
                        Lien
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

