<?php $marque = $this->getCurrentMarque(); ?>

<?php if($marque->getName()): ?>
  <h1>Produits <?php echo $marque->getName(); ?> :</h1>

	<?php $productsAssociated = Mage::Helper("virtual_marques")->getProductsByMarque($marque->getId()); ?>
      <?php foreach ($productsAssociated as $asso): ?>
	    	<?php $idProduct = $asso["product_id"]; ?>
	    	<?php $product = $product = Mage::getModel('catalog/product')->load($idProduct); ?>
        <div style="margin-top:10px; margin-bottom:10px;">
  	    	<img src="<?php echo Mage::getBaseUrl().'media/catalog/product'.$product->getImage(); ?>" >
  	    	<h2><?php echo $product->getName(); ?></h2>
  	    	<h3><?php echo round($product->getPrice(),2) . 'euros'; ?></h3>
  	    	<a href="<?php echo Mage::getBaseUrl().$product->getUrlPath(); ?>" class="button">Acheter</a>
        </div>
        <hr>
      <?php endforeach; ?>
<?php else: ?>
  <h1>Ce produit n'existe pas</h1>

<?php endif; ?>
