<?php $marque = $this->getCurrentMarque(); ?>

<h1>Produits :</h1>
<?php echo $marque; ?>

<?php $productsAssociated = Mage::Helper("virtual_marques")->getProductsByMarque($marque->getId()); ?>
    <?php foreach ($productsAssociated as $asso): ?>
    	<?php $idProduct = $asso["product_id"]; ?>
    	<?php $product = $product = Mage::getModel('catalog/product')->load($idProduct); ?>
    	<img src="<?php echo Mage::getBaseUrl().'media/catalog/product'.$product->getImage(); ?>" >
    	<?php echo $product->getName(); ?>
    	<?php echo round($product->getPrice(),2); ?>
    	<a href="<?php echo Mage::getBaseUrl().$product->getUrlPath(); ?>" class="button">Acheter</a>
    <?php endforeach; ?>
